# Generated by Django 3.1.2 on 2021-01-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(choices=[('kg', 'кг'), ('item', 'шт'), ('pack', 'упаковка')], max_length=6, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Единицы измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_type', models.CharField(choices=[('bag', 'мешки'), ('box', 'ящики')], max_length=6, verbose_name='Тип тары')),
            ],
            options={
                'verbose_name': 'Тип тары',
                'verbose_name_plural': 'Типы тары',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppler_name', models.CharField(max_length=50, verbose_name='Имя поставщика:')),
                ('supplier_mobile', models.PositiveIntegerField(max_length=9, verbose_name='Телефон поставщика: +380')),
                ('suppler_email', models.EmailField(max_length=254, verbose_name='@mail:')),
                ('supplier_status', models.BooleanField(default=True, verbose_name='Статус "Поставщик"')),
                ('customer_status', models.BooleanField(default=False, verbose_name='Статус "Покупатель"')),
                ('loyalty_status', models.BooleanField(default=False, verbose_name='Является участником программы лояльности')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['suppler_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('mailing_status', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landingby.producttype', verbose_name='Тип тары')),
                ('supplier_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landingby.supplier', verbose_name='Номер поставщика')),
                ('units_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landingby.measure', verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Заказ на продажу',
                'verbose_name_plural': 'Заказы на продажу',
            },
        ),
    ]
