# Generated by Django 3.1.2 on 2021-01-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_mobile',
            field=models.PositiveIntegerField(verbose_name='Телефон поставщика: +380'),
        ),
    ]
