# Generated by Django 3.1.2 on 2021-01-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0002_auto_20210128_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='supplier_ID',
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='units',
            field=models.CharField(choices=[('кг', 'кг'), ('шт', 'шт'), ('упаковка', 'упаковка')], max_length=15, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='prod_type',
            field=models.CharField(choices=[('мешки', 'пп. мешки'), ('ящики', 'пп. ящики')], max_length=15, verbose_name='Тип тары'),
        ),
    ]
