# Generated by Django 3.1.2 on 2021-01-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0003_auto_20210129_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='supplier_name',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.PROTECT, to='landingby.supplier', verbose_name='Имя поставщика'),
            preserve_default=False,
        ),
    ]
