# Generated by Django 3.1.2 on 2021-02-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0004_productorder_supplier_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Заказ на продажу', 'verbose_name_plural': 'Всего заказов на продажу'},
        ),
        migrations.AlterField(
            model_name='producttype',
            name='prod_type',
            field=models.CharField(choices=[('мешки', 'мешки'), ('ящики', 'ящики')], max_length=15, verbose_name='Тип тары'),
        ),
    ]
