# Generated by Django 3.1.2 on 2021-02-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0005_auto_20210201_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Заказ на продажу', 'verbose_name_plural': 'Заказы на продажу'},
        ),
    ]
