# Generated by Django 3.1.2 on 2021-02-01 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0007_auto_20210201_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='order_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
