# Generated by Django 3.1.2 on 2021-02-08 13:32

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0008_productorder_order_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='product_order_id',
        ),
        migrations.AddField(
            model_name='productorder',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
