# Generated by Django 3.1.2 on 2021-02-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0010_auto_20210209_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='order_datetime',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
    ]
