# Generated by Django 3.1.2 on 2021-02-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0011_auto_20210214_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='order_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
    ]
