# Generated by Django 3.1.2 on 2021-06-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0013_auto_20210520_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='@mail:'),
        ),
    ]
