# Generated by Django 3.1.2 on 2021-06-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingby', '0017_auto_20210602_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landingby.supplier', verbose_name='Имя поставщика'),
        ),
    ]
